/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Util_SoundAdminUtil */

#ifndef _Included_Util_SoundAdminUtil
#define _Included_Util_SoundAdminUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Util_SoundAdminUtil
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Util_SoundAdminUtil_init
  (JNIEnv *, jobject);

/*
 * Class:     Util_SoundAdminUtil
 * Method:    setMasterVolume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Util_SoundAdminUtil_setMasterVolume
  (JNIEnv *, jobject, jint);

/*
 * Class:     Util_SoundAdminUtil
 * Method:    getMasterVolume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Util_SoundAdminUtil_getMasterVolume
  (JNIEnv *, jobject);

/*
 * Class:     Util_SoundAdminUtil
 * Method:    setMute
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_Util_SoundAdminUtil_setMute
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     Util_SoundAdminUtil
 * Method:    getMute
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Util_SoundAdminUtil_getMute
  (JNIEnv *, jobject);

/*
 * Class:     Util_SoundAdminUtil
 * Method:    finished
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Util_SoundAdminUtil_finished
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
